server :
  port : 8888

spring:
  application:
    name: configuration-server
  cloud :
    server :
      git :
        uri : git@github.com-work:manikrish-tech/fc-config-server.git
        default-label : main
        ignore-local-ssh-settings : true
        private-key : ${SSH_PRIVATE_KEY:}
        search-paths : '{application}'
        clone-on-start : true

eureka:
  client :
    service-url :
      defaultZone : http://service-registry:8761/eureka/