# Service-specific development configuration
server:
  port: 8084  # This will be different for each service

spring:
  application:
    name: account-server
  datasource:
    url: jdbc:postgresql://postgres:5432/fcdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000
#      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE