# Service-specific development configuration for transaction-service
server:
  port: 8016  # This will be different for each service

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fcdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,refresh
  endpoint:
    health:
      show-details: always