# Service-specific test configuration for transaction service
server:
  port: 8009  # Different from dev and prod

spring:
  application:
    name: transaction-service

datasource:
  url: jdbc:postgresql://localhost:5433/test_transaction_service_db
  username: test_user
  password: test_password
  driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: validate
  show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management :
  endpoint :
    health :
      show-details : always
    end-points :
      web :
        exposure :
          include  : health,info,metrics,loggers,env