# Service-specific production configuration for transaction service
server:
  port: 8008  # Set the appropriate production port

spring:
  application:
    name: transaction-service

datasource:
  url: jdbc:postgresql://prod-db-host:5434/transaction_service_db
  username: prod_user
  password: prod_password
  driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: none
  show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka.prod-cluster.internal:8761/eureka/
