server:
  port: 8762  # Different port for test environment

spring:
  application:
    name: service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,refresh
  endpoint:
    health:
      show-details: always