server:
  port: 8762  # Different port for test environment

spring:
  application:
    name: service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management :
  endpoint :
    health :
      show-details : always
    end-points :
      web :
        exposure :
          include  : *